-- EduPlan namuna maktab ma'lumoti (5-11 sinf)
-- seed_data.py dan avtomatik generatsiya qilingan. Qo'lda tahrirlamang.
-- Yuklash: psql -h localhost -U postgres -d maktab_db -f seed.sql

BEGIN;

-- Eski ma'lumotni tozalash va id larni qayta 1 dan boshlash
TRUNCATE TABLE schedule, teacher_subjects, teacher_classes,
    subject_grades, subjects, classes, rooms, teachers
    RESTART IDENTITY CASCADE;

-- Fanlar (id tartibi seed_data.SUBJECTS bilan bir xil)
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Ona tili', 3, 4, 'morning');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Adabiyot', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Matematika', 3, 5, 'morning');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Algebra', 3, 5, 'morning');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Geometriya', 3, 5, 'morning');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Fizika', 3, 5, 'morning');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Kimyo', 3, 5, 'morning');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Biologiya', 3, 4, 'morning');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Geografiya', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Tarix', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('O''zbekiston tarixi', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Jahon tarixi', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Ingliz tili', 3, 4, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Rus tili', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Informatika', 3, 4, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Tarbiya', 3, 2, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Jismoniy tarbiya', 3, 2, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Chizmachilik', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Tasviriy san''at', 3, 2, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Musiqa', 3, 2, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Texnologiya', 3, 2, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Iqtisodiy bilim asoslari', 3, 3, 'any');
INSERT INTO subjects (name, weekly_hours, difficulty, preferred_time) VALUES ('Huquq', 3, 3, 'any');

-- Sinf-fan-soat (qaysi fan qaysi sinfga, haftasiga necha soat)
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (1, 5, 4);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (2, 5, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (3, 5, 5);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (13, 5, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (14, 5, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (10, 5, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (9, 5, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (8, 5, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (15, 5, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (19, 5, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (20, 5, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (17, 5, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (21, 5, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (16, 5, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (1, 6, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (2, 6, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (3, 6, 5);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (13, 6, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (14, 6, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (10, 6, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (9, 6, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (8, 6, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (15, 6, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (19, 6, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (20, 6, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (17, 6, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (21, 6, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (16, 6, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (1, 7, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (2, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (4, 7, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (5, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (6, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (13, 7, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (14, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (10, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (9, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (8, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (15, 7, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (18, 7, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (17, 7, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (21, 7, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (16, 7, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (1, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (2, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (4, 8, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (5, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (6, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (7, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (13, 8, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (14, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (10, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (9, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (8, 8, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (15, 8, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (18, 8, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (17, 8, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (16, 8, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (1, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (2, 9, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (4, 9, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (5, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (6, 9, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (7, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (13, 9, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (14, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (11, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (12, 9, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (9, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (8, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (15, 9, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (17, 9, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (1, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (2, 10, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (4, 10, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (5, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (6, 10, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (7, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (13, 10, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (14, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (11, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (12, 10, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (9, 10, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (8, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (15, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (17, 10, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (22, 10, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (23, 10, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (1, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (2, 11, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (4, 11, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (5, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (6, 11, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (7, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (13, 11, 3);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (14, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (11, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (12, 11, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (8, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (15, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (17, 11, 2);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (22, 11, 1);
INSERT INTO subject_grades (subject_id, grade, weekly_hours) VALUES (23, 11, 1);

-- O'qituvchilar (id tartibi seed_data.TEACHERS bilan bir xil)
INSERT INTO teachers (name, phone) VALUES ('Aziza Karimova', '+998901112201');
INSERT INTO teachers (name, phone) VALUES ('Dilnoza Yusupova', '+998901112202');
INSERT INTO teachers (name, phone) VALUES ('Bahrom Rashidov', '+998901112203');
INSERT INTO teachers (name, phone) VALUES ('Sardor Aliyev', '+998901112204');
INSERT INTO teachers (name, phone) VALUES ('Gulnora Tosheva', '+998901112205');
INSERT INTO teachers (name, phone) VALUES ('Jasur Ergashev', '+998901112206');
INSERT INTO teachers (name, phone) VALUES ('Nodira Saidova', '+998901112207');
INSERT INTO teachers (name, phone) VALUES ('Feruza Qodirova', '+998901112208');
INSERT INTO teachers (name, phone) VALUES ('Otabek Nazarov', '+998901112209');
INSERT INTO teachers (name, phone) VALUES ('Malika Umarova', '+998901112210');
INSERT INTO teachers (name, phone) VALUES ('Shahzod Kamolov', '+998901112211');
INSERT INTO teachers (name, phone) VALUES ('Kamola Ismoilova', '+998901112212');
INSERT INTO teachers (name, phone) VALUES ('Elena Petrova', '+998901112213');
INSERT INTO teachers (name, phone) VALUES ('Ulug''bek Tursunov', '+998901112214');
INSERT INTO teachers (name, phone) VALUES ('Zarina Hakimova', '+998901112215');
INSERT INTO teachers (name, phone) VALUES ('Rustam Qosimov', '+998901112216');
INSERT INTO teachers (name, phone) VALUES ('Laziz Mahmudov', '+998901112217');
INSERT INTO teachers (name, phone) VALUES ('Sevara Abdullayeva', '+998901112218');
INSERT INTO teachers (name, phone) VALUES ('Bekzod Sobirov', '+998901112219');
INSERT INTO teachers (name, phone) VALUES ('Mehriniso Yo''ldosheva', '+998901112220');

-- O'qituvchi-fan biriktirish (qaysi o'qituvchi qaysi fanni o'qitadi)
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (1, 1);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (1, 2);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (2, 1);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (2, 2);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (3, 3);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (3, 4);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (4, 3);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (4, 5);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (5, 4);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (5, 5);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (6, 6);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (7, 7);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (8, 8);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (9, 9);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (10, 10);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (10, 11);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (10, 12);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (11, 13);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (12, 13);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (13, 14);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (14, 15);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (15, 15);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (16, 17);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (17, 17);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (18, 20);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (18, 19);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (19, 21);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (19, 18);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (20, 16);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (20, 23);
INSERT INTO teacher_subjects (teacher_id, subject_id) VALUES (20, 22);

-- Sinflar (5-A ... 11-B) — sinf rahbari (class_teacher_id) bilan
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('5-A', 5, 'A', 30, 1, 1);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('5-B', 5, 'B', 30, 1, 2);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('6-A', 6, 'A', 30, 1, 3);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('6-B', 6, 'B', 30, 1, 4);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('7-A', 7, 'A', 30, 1, 5);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('7-B', 7, 'B', 30, 1, 6);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('8-A', 8, 'A', 30, 1, 7);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('8-B', 8, 'B', 30, 1, 8);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('9-A', 9, 'A', 30, 1, 9);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('9-B', 9, 'B', 30, 1, 10);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('10-A', 10, 'A', 30, 1, 11);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('10-B', 10, 'B', 30, 1, 12);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('11-A', 11, 'A', 30, 1, 13);
INSERT INTO classes (name, grade, section, student_count, shift, class_teacher_id) VALUES ('11-B', 11, 'B', 30, 1, 14);

-- Xonalar (oddiy sinf xonalari + amaliy fan laboratoriyalari)
INSERT INTO rooms (name, capacity) VALUES ('101-xona (5-A)', 30);
INSERT INTO rooms (name, capacity) VALUES ('102-xona (5-B)', 30);
INSERT INTO rooms (name, capacity) VALUES ('103-xona (6-A)', 30);
INSERT INTO rooms (name, capacity) VALUES ('104-xona (6-B)', 30);
INSERT INTO rooms (name, capacity) VALUES ('105-xona (7-A)', 30);
INSERT INTO rooms (name, capacity) VALUES ('106-xona (7-B)', 30);
INSERT INTO rooms (name, capacity) VALUES ('107-xona (8-A)', 30);
INSERT INTO rooms (name, capacity) VALUES ('108-xona (8-B)', 30);
INSERT INTO rooms (name, capacity) VALUES ('109-xona (9-A)', 30);
INSERT INTO rooms (name, capacity) VALUES ('110-xona (9-B)', 30);
INSERT INTO rooms (name, capacity) VALUES ('111-xona (10-A)', 30);
INSERT INTO rooms (name, capacity) VALUES ('112-xona (10-B)', 30);
INSERT INTO rooms (name, capacity) VALUES ('113-xona (11-A)', 30);
INSERT INTO rooms (name, capacity) VALUES ('114-xona (11-B)', 30);
INSERT INTO rooms (name, capacity) VALUES ('Fizika laboratoriyasi', 30);
INSERT INTO rooms (name, capacity) VALUES ('Kimyo laboratoriyasi', 30);
INSERT INTO rooms (name, capacity) VALUES ('Biologiya laboratoriyasi', 30);
INSERT INTO rooms (name, capacity) VALUES ('Informatika xonasi 1', 24);
INSERT INTO rooms (name, capacity) VALUES ('Informatika xonasi 2', 24);
INSERT INTO rooms (name, capacity) VALUES ('Sport zali', 60);
INSERT INTO rooms (name, capacity) VALUES ('Musiqa xonasi', 30);
INSERT INTO rooms (name, capacity) VALUES ('Texnologiya ustaxonasi (o''g''il)', 25);
INSERT INTO rooms (name, capacity) VALUES ('Texnologiya xonasi (qiz)', 25);

COMMIT;
